// Tauri build script.
//
// The app defines an ACL manifest for its own commands: tauri-build generates an
// `allow-<command>` / `deny-<command>` permission for each name below (command
// name with `_` replaced by `-`, written to permissions/autogenerated, which is
// gitignored). The UI is served by the bundled Next server at
// http://127.0.0.1:3000, a REMOTE origin to Tauri, and Tauri rejects every IPC
// call from a remote origin that resolves to no capability, app commands
// included ("Command ... not allowed by ACL"). capabilities/desktop-ui.json
// grants exactly these permissions to that origin.
//
// Keep this list equal to the commands in `generate_handler!` (src/main.rs);
// tests/backend/test_desktop_packaging.py fails when they differ.
const APP_COMMANDS: &[&str] = &[
    "quit_now",
    "check_for_update",
    "install_update_and_restart",
    "get_update_status",
    "set_update_channel",
    "confirm_browser_tier",
    "confirm_browser_pairing",
    "confirm_action",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("failed to run the Tauri build script");
}
