"""The backend build version embedded in the desktop sidecar (LOCUS-349, D-26).

The desktop shell passes its own version to the sidecar as ``LOCUS_APP_VERSION``,
so that variable cannot tell a stale sidecar from a fresh one (tauri#15134: an
NSIS update can leave the previous ``locus-backend`` in place). The release
workflow therefore stamps the version it builds into ``_build_stamp.py`` before
PyInstaller runs::

    python -m locus_tooling.build_info 0.1.0-dev.42

and the shell compares the stamped version with its own after every start. A
source checkout or a local build has no stamp (``""``).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

#: Semantic version as the Tauri updater parses it (no leading ``v``).
SEMVER_RE = re.compile(
    r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)"
    r"(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?\Z"
)
STAMP_FILE = Path(__file__).with_name("_build_stamp.py")


def is_semver(value: str) -> bool:
    return bool(SEMVER_RE.match(str(value or "").strip()))


def backend_build_version() -> str:
    """The version CI stamped into this build, or ``""`` when unstamped."""
    try:
        from locus_tooling._build_stamp import BUILD_VERSION  # type: ignore[import-not-found]
    except ImportError:
        return ""
    value = str(BUILD_VERSION or "").strip()
    return value if is_semver(value) else ""


def stamp_build_version(version: str, path: Path = STAMP_FILE) -> Path:
    """Write the stamp module. Only a valid semantic version is written."""
    value = str(version or "").strip()
    if not is_semver(value):
        raise ValueError(f"not a semantic version: {value!r}")
    path.write_text(
        '"""Generated by `python -m locus_tooling.build_info` in CI; do not commit."""\n\n'
        f"BUILD_VERSION = {value!r}\n",
        encoding="utf-8",
    )
    return path


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) != 1:
        print("usage: python -m locus_tooling.build_info <version>", file=sys.stderr)
        return 2
    try:
        path = stamp_build_version(args[0])
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    print(f"stamped {args[0]} into {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
