"""Bounded parsing and issue text for empty-queue research cycles."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any

from locus_runtime.loop_runner.feedback import sanitize_untrusted


@dataclass(frozen=True)
class ResearchProposal:
    title: str
    hypothesis: str
    change: str
    test_case: str
    falsifier: str
    priority: int


def parse_research_proposals(text: str, *, limit: int = 3) -> list[ResearchProposal]:
    """Accept only concise, testable proposals from the local planner response."""
    raw = str(text or "").strip()
    if raw.startswith("```"):
        raw = re.sub(r"^```(?:json)?\s*|\s*```$", "", raw, flags=re.IGNORECASE).strip()
    payload: Any = None
    try:
        payload = json.loads(raw)
    except ValueError:
        decoder = json.JSONDecoder()
        for index, char in enumerate(raw):
            if char != "{":
                continue
            try:
                payload, _end = decoder.raw_decode(raw[index:])
                break
            except ValueError:
                continue
    entries = payload.get("items") if isinstance(payload, dict) else None
    if not isinstance(entries, list):
        return []
    proposals: list[ResearchProposal] = []
    seen: set[str] = set()
    max_results = max(0, min(5, int(limit)))
    if not max_results:
        return []
    for entry in entries[: min(20, max_results * 5)]:
        if not isinstance(entry, dict):
            continue
        title = sanitize_untrusted(entry.get("title"), 120)
        hypothesis = sanitize_untrusted(entry.get("hypothesis"), 500)
        change = sanitize_untrusted(entry.get("change"), 1000)
        test_case = sanitize_untrusted(entry.get("test_case"), 800)
        falsifier = sanitize_untrusted(entry.get("falsifier"), 500)
        fingerprint = re.sub(r"[^a-z0-9]+", " ", title.lower()).strip()
        if not title or not hypothesis or not change or not test_case or not falsifier:
            continue
        if len(title) < 12 or fingerprint in seen:
            continue
        seen.add(fingerprint)
        try:
            priority = int(entry.get("priority") or 3)
        except (TypeError, ValueError):
            priority = 3
        proposals.append(
            ResearchProposal(
                title=title,
                hypothesis=hypothesis,
                change=change,
                test_case=test_case,
                falsifier=falsifier,
                priority=min(4, max(2, priority)),
            )
        )
    return sorted(proposals, key=lambda item: (item.priority, item.title.lower()))[:max_results]


def issue_description(proposal: ResearchProposal) -> str:
    return "\n".join(
        [
            "## Research hypothesis",
            proposal.hypothesis,
            "",
            "## Proposed change",
            proposal.change,
            "",
            "## Test case",
            proposal.test_case,
            "",
            "## Falsification criterion",
            proposal.falsifier,
            "",
            "## Validation",
            "Add a deterministic regression test for the test case. The Locus loop will run the repository's required checks and configured RSI scorecard before it proposes a pull request. A failed test or non-improving scorecard invalidates this hypothesis and blocks delivery.",
            "",
            "Generated by the bounded empty-queue research mode. Review the evidence and scope before broadening the change.",
        ]
    )[:8000]
